In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,"fgsj",True]])
print(arr)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[['1' '2' '3' '4']
 ['5' '6' 'fgsj' 'True']]
8
2
<U21


In [6]:
arr2=np.array([[1,"Aby","Male"],[2,"Biby","Male"]])
print(arr2)

[['1' 'Aby' 'Male']
 ['2' 'Biby' 'Male']]


In [8]:
arr3=np.zeros((3,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [80]:
hi=np.linspace(1,50)
print(hi)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [41]:
print(np.random.rand(3,2))

[[0.03976744 0.24159851]
 [0.46713177 0.82127043]
 [0.08647933 0.24491936]]


In [42]:
print(np.random.randn(3,2))

[[-0.34994239  1.13492722]
 [ 0.2139501  -0.41193856]
 [ 0.07050066  1.03430388]]


In [67]:
arr4=np.array([[True,False,True],[1,2,3]])
print(arr4)

[[1 0 1]
 [1 2 3]]


In [68]:
print(arr4.shape)

(2, 3)


In [69]:
print(arr4.ndim)

2


In [70]:
print(arr3.size)
print(arr4.dtype)

9
int64


In [94]:
a=np.array([1,2,3])
b=np.array([4,5,6,])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
sinarr=np.array([0.523599,45,60,1.570796]) #Angle should be in radians for sin
print(np.sin(a))
print(np.sin(sinarr))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0.84147098 0.90929743 0.14112001]
[ 0.50000019  0.85090352 -0.30481062  1.        ]


In [104]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(a,b))
a@b
print(np.dot(A,B))
A@B

32
[[19 22]
 [43 50]]


array([[19, 22],
       [43, 50]])

In [109]:
arr5=np.array([1,2,3,4,5])
print(arr5.sum())
print(arr5.mean())
print(arr5.min())
print(arr5.max())
print(arr5.std())

15
3.0
1
5
1.4142135623730951


In [116]:
print(arr5[0])
print(arr5[1:4])
print(arr5[::2])

1
[2 3 4]
[1 3 5]


In [117]:
arr6 = np.array([[1, 2, 3], [4, 5, 6]])

In [129]:
print(arr6[0,1])
print(arr6[:,1])
print(arr6[1,1:])

2
[2 5]
[5 6]


In [131]:
mask=arr5>3
arr5[mask]

array([4, 5])

In [144]:
arr7=np.arange(6)
print(arr7)


[0 1 2 3 4 5]


In [145]:
arr8=arr7.reshape(2,3)
print(arr8)

[[0 1 2]
 [3 4 5]]


In [147]:
arr7.resize(2,3)
print(arr7)

[[0 1 2]
 [3 4 5]]


In [148]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [152]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [153]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [154]:
a=np.array([1,2,3])
a+5

array([6, 7, 8])

In [155]:
np.save('array.npy',arr)

In [156]:
loaded_arr=np.load('array.npy')
print(loaded_arr)

[['1' '2' '3' '4']
 ['5' '6' 'fgsj' 'True']]
